version: '3.8'

services:
  db:
    container_name: postgredb
    image: postgres:13 
    environment:
      - POSTGRES_DB=brewerydb
      - POSTGRES_USER=lofrey
      - POSTGRES_PASSWORD=lofrey
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./sql/brewerydb.sql:/docker-entrypoint-initdb.d/brewerydb.sql    
      - ./files:/files
    ports:
      - "55432:5432"
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lofrey -d brewerydb"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=lofrey@lofrey.com
      - PGADMIN_DEFAULT_PASSWORD=lofrey
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - app_network
    depends_on:
      - db
    restart: always

  # --- AIRFLOW ---
  airflow-init:
  
    image: apache/airflow:2.9.2
    depends_on:
      db:
        condition: service_healthy 
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://lofrey:lofrey@db:5432/brewerydb
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    command: bash -c "airflow db init && airflow users create --role Admin --username admin --password admin --email admin@example.com --firstname admin --lastname admin"
    networks:
      - app_network
    restart: on-failure

  airflow-webserver:
    image: apache/airflow:2.9.2
    depends_on:
      - airflow-init
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://lofrey:lofrey@db:5432/brewerydb
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__WEBSERVER__SECRET_KEY=lofrey
    command: airflow webserver
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

  airflow-scheduler:
    build: .
    depends_on:
      airflow-webserver:
        condition: service_healthy 
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://lofrey:lofrey@db:5432/brewerydb
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    command: airflow scheduler
    networks:
      - app_network
    restart: always

# Redes e Volumes
networks:
  app_network:
    driver: bridge

volumes:
  postgresql_data:
  pgadmin_data: